framework:
    secret: '%env(APP_SECRET)%'
    esi: { enabled: true }
    fragments: { path: /_fragment }
    csrf_protection: true
    error_controller: App\Controller\ExceptionController::showAction
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.

    session:
        handler_id: ~
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: ~ # possible values: 'strict', 'lax' and null
        storage_id: cms.session.storage.dynamic_domain # default: session.storage.mock_file

    #esi: true
    #fragments: true
    php_errors:
        log: true

services:
    cms.session.storage.dynamic_domain:
        class: App\EventSubscriber\DomainSessionStorage