monolog:

    handlers:

        main:
            type: rotating_file
            max_files: 15
            path: '%kernel.logs_dir%/%kernel.environment%.main.log'
            level: debug
            channels: ["!event", '!security']

        cache_helper:
            type: stream
            path: "%kernel.logs_dir%/cache-helper.log"
            level: debug
            channels: ["cache_helper"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

        security:
            type: rotating_file
            max_files: 15
            path: '%kernel.logs_dir%/%kernel.environment%.security.log'
            level: debug
            channels: security

        error:
            type: rotating_file
            max_files: 15
            path: '%kernel.logs_dir%/%kernel.environment%.error.log'
            level: critical
            channels: ['!security']