doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: 'mysql://%env(DB_USER_LOCAL)%:%env(DB_PASSWORD_LOCAL)%@%env(DB_HOST_LOCAL)%:%env(DB_PORT_LOCAL)%/%env(DB_NAME_LOCAL)%'
#            direct:
#                url: 'mysql://%env(DB_USER_DIRECT_LOCAL)%:%env(DB_PASSWORD_DIRECT_LOCAL)%@%env(DB_HOST_DIRECT_LOCAL)%:%env(DB_PORT_DIRECT_LOCAL)%/%env(DB_NAME_DIRECT_LOCAL)%'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
#            direct:
#                connection: direct